### ISSUE TITLE
Update peer dependency comatibility

### ISSUE THREAD

**Issue by m10** [filipekiss/stylelint-color-format#8]
Currently it is not compatible with stylelint 12+

npm WARN stylelint-color-format@0.2.0 requires a peer of stylelint@^8.0.0 || ^9.0.0 but none is installed. You must install peer dependencies yourself.

A new release to npm will also be necessary

**Comment by filipekiss** [comment]
I've updated the `package.json` and release the version 1.0.0 on [npm](https://www.npmjs.com/package/stylelint-color-format). Thanks for the heads up :D
