### ISSUE TITLE
Custom message

### ISSUE THREAD

**Issue by BorisZubchenko** [filipekiss/stylelint-color-format#9]
Please, add the ability to provide custom error message or if it's already implemented, add docs. I tried the following but unsuccessfully:
```
"color-format/format": {
  "format": "hsl",
  "message": "Consider using HSL."
}
```
```
"color-format/format": [{
  "format": "hsl",
  "message": "Consider using HSL."
}]
```
```
"color-format/format": {
  "format": "hsl",
  "message": "Consider using HSL."
}
```
```
"color-format/format": [
  "hsl",
  {
    "message": "Consider using HSL."
  }
]
```

**Comment by filipekiss** [comment]
Hey @BorisZubchenko, thanks for the report. We currently don't have message support, but I'll try to add it soon!

**Comment by filipekiss** [comment]
Thank you for your suggestion @BorisZubchenko!

Version v1.1.0 is [available on npm](https://www.npmjs.com/package/stylelint-color-format/v/1.1.0)
